### ISSUE TITLE
Error in summaryData: Supplied 2 items to be assigned to 3 items of column 'S'

### ISSUE THREAD

**Issue by Lobz** [LimaRAF/plantR#158]
I'm getting this error with some subsets of my data but not others. I made a small file to reproduce the error. This file has already passed through the default plantR workflow.

[test_data_error_summaryData.csv](https://github.com/user-attachments/files/19779604/test_data_error_summaryData.csv)

Run the following code:
```r
occs <- read.csv("test_data_error_summaryData.csv")
summ <- summaryData(occs)
```
Outputs the following:
```
=========
 RECORDS 
=========
|Type                     | Records|
|:------------------------|-------:|
|Unicates                 |       3|
|Duplicates               |       0|
|Unknown                  |       0|
|Total without duplicates |       3|
|Total with duplicates    |       3|

=============
 COLLECTIONS 
=============
Number of biological collections: 1 
Number of collectors' names: 2 
Collection years: 2014-2014 (>90% and >50% after 2014 and 2014)

Top collections in numbers of records:
|Collection | Records|
|:----------|-------:|
|SPSF       |       3|

Top collectors in numbers of records:
|Collector       | Records|
|:---------------|-------:|
|Cielo Filho, R. |       2|
|Baitello, J.B.  |       1|

==========
 TAXONOMY 
==========
Error in `[.data.table`(fams, , `:=`(S, dt[genus.only, data.table::uniqueN(.SD),  : 
  Supplied 2 items to be assigned to 3 items of column 'S'. If you wish to 'recycle' the RHS please use rep() to make this intent clear to readers of your code.
```

**Comment by LimaRAF** [comment]
There was a small bug related to a missing logical vector in one of the operations. Should be fixed now (see my output below after the changes). I also fixed some bugs in the print of the number of families and genus, related to families that have only records at the genus level. Please check if this is solved for you as well so we can close this issue.

```
> occs <- read.csv("data-raw/test_data_error_summaryData.csv")
> summ <- summaryData(occs)
=========
 RECORDS 
=========
|Type                     | Records|
|:------------------------|-------:|
|Unicates                 |       3|
|Duplicates               |       0|
|Unknown                  |       0|
|Total without duplicates |       3|
|Total with duplicates    |       3|

=============
 COLLECTIONS 
=============
Number of biological collections: 1 
Number of collectors' names: 2 
Collection years: 2014-2014 (>90% and >50% after 2014 and 2014)

Top collections in numbers of records:
|Collection | Records|
|:----------|-------:|
|SPSF       |       3|

Top collectors in numbers of records:
|Collector       | Records|
|:---------------|-------:|
|Cielo Filho, R. |       2|
|Baitello, J.B.  |       1|

==========
 TAXONOMY 
==========
Number of families: 3 
Number of genera: 3 
Number of species: 2 

Top richest families:
|family.new  | Records| Taxa|
|:-----------|-------:|----:|
|Fabaceae    |       1|    1|
|Poaceae     |       1|    1|
|Sapindaceae |       1|    0|

Top richest genera:
|genus.new | Records| Taxa|
|:---------|-------:|----:|
|Senna     |       1|    1|
|Serjania  |       1|    1|
|Setaria   |       1|    1|

===========
 COUNTRIES 
===========
Number of countries: 1 

Top countries in numbers of records:
|Country | Records| Taxa|
|:-------|-------:|----:|
|Brazil  |       3|    3|
```

**Comment by Lobz** [comment]
It seems to have worked with this specific test data but not in general. Here's a new test data file where the error remains:

[test_data_error_summaryData.csv](https://github.com/user-attachments/files/19856124/test_data_error_summaryData.csv)

**Comment by LimaRAF** [comment]
Hi and thanks again. I am now creating the counts of number of species in a separate table and then merging with the counts of number of records per family, which should be safer. No longer sure why I wanted to print the results for number of taxa identified at the genus and species level separately, but it is probably to avoid an inflation of the number of genera per family (Serjania being count twice in the case of having Serjania and Serjania something, which could actually be the same thing).

I ran the tests with both datasets you shared with me and they both work out for me. Hope it is alright now.

```

> occs <- read.csv("data-raw/test_data_error_summaryData.csv")
> summ <- summaryData(occs)
=========
 RECORDS 
=========
|Type                     | Records|
|:------------------------|-------:|
|Unicates                 |       4|
|Duplicates               |       0|
|Unknown                  |       0|
|Total without duplicates |       4|
|Total with duplicates    |       4|

=============
 COLLECTIONS 
=============
Number of biological collections: 1 
Number of collectors' names: 2 
Collection years: 2014-2014 (>90% and >50% after 2014 and 2014)

Top collections in numbers of records:
|Collection | Records|
|:----------|-------:|
|SPSF       |       4|

Top collectors in numbers of records:
|Collector       | Records|
|:---------------|-------:|
|Baitello, J.B.  |       3|
|Cielo Filho, R. |       1|

==========
 TAXONOMY 
==========
Number of families: 3 
Number of genera: 4 
Number of species: 4 

Top richest families:
|family.new | Records| Taxa|
|:----------|-------:|----:|
|Fabaceae   |       2|    2|
|Poaceae    |       1|    1|
|Rubiaceae  |       1|    1|

Top richest genera:
|genus.new  | Records| Taxa|
|:----------|-------:|----:|
|Amaioua    |       1|    1|
|Andira     |       1|    1|
|Andropogon |       1|    1|
|Bauhinia   |       1|    1|

===========
 COUNTRIES 
===========
Number of countries: 1 

Top countries in numbers of records:
|Country | Records| Taxa|
|:-------|-------:|----:|
|Brazil  |       4|    4|

```

**Comment by Lobz** [comment]
Thanks! Seems like the issue is solved
